version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: my-db
    environment:
      MYSQL_DATABASE: 'devbook'
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - G:\Biblioteca\Documentos\dumps\Dump20240322:/docker-entrypoint-initdb.d
    networks:
      - devbook-network

  api:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: devbook-api
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      API_PORT: ${API_PORT}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - devbook-network

volumes:
  db-data:

networks:
  devbook-network:
    name: devbook-network
